"""Final title tags (≤ 70 characters; home ≤ 90) and meta descriptions (≤ 160) by slug, following the audit's Appendix C.

Kept in one place so they can be tuned without touching page copy. Applied by base.page().
"""
CAR = "practice-areas/car-accidents"
META = {
    "home": ("Summerville Car Accident & Personal Injury Lawyers | Frost Law Group",
             "Injured in Summerville, SC? Frost Law Group handles car, truck, motorcycle, dog bite and wrongful death claims. Free consultation, no fee unless we win."),
    "practice-areas": ("Personal Injury Practice Areas | Summerville, SC | Frost Law Group",
                       "Car, truck, motorcycle, pedestrian and rideshare crashes, drunk-driving victims, dog bites, slip and fall, workers' comp and wrongful death in Summerville, SC."),
    "areas": ("Areas We Serve | Summerville, Goose Creek, Charleston & the Lowcountry",
              "Injury lawyers for Summerville, Goose Creek, Ladson, North Charleston, Charleston, Mount Pleasant, Moncks Corner, Walterboro and West Ashley, SC."),
    "about": ("Our Attorneys | Jack & Tara Frost | Summerville Accident Attorneys",
              "Tara Frost, a former Dorchester County magistrate judge, leads Frost Law Group's injury practice; Jack Frost, a former detective, runs the investigation."),
    "attorneys/tara-frost": ("Tara L. Frost | Summerville Personal Injury Attorney | Former Judge",
                             "Tara L. Frost leads Frost Law Group's injury practice in Summerville, SC. She served as a Dorchester County Magistrate Judge and Associate Probate Judge."),
    "attorneys/jack-frost": ("Jack C. Frost | Former Detective | Summerville Accident Attorneys",
                             "Jack C. Frost spent 14 years as a Summerville police officer and Charleston County detective. He now investigates crash and injury cases for Frost Law Group."),
    "contact": ("Free Consultation | Summerville Accident Attorneys | 843-419-6653",
                "Call (843) 419-6653 for a free injury consultation with Frost Law Group, 128 Linwood Lane, Summerville, SC. No fee unless we win. Directions and a contact form."),
    "reviews": ("Client Reviews | Summerville Accident Attorneys | Frost Law Group",
                "What injured clients and their families say about working with Tara and Jack Frost in Summerville, SC, and how to leave a review on Google or Yelp."),
    "blog": ("Blog | Accident & Injury Questions Answered by Summerville Attorneys",
             "What Lowcountry news means for a crash claim, a dog-bite case or an insurance dispute, written by Summerville injury attorney Tara Frost."),
    "privacy-policy": ("Privacy Policy | Summerville Accident Attorneys | Frost Law Group",
                       "How summervilleaccidentattorney.com handles the information you share through its contact form, the click-to-load map and server logs, and what we never do."),
    "terms-of-use": ("Terms of Use & Legal Disclaimer | Summerville Accident Attorneys",
                     "The rules for using summervilleaccidentattorney.com: attorney advertising notice, no legal advice, no attorney-client relationship until engagement, fees."),
    "accessibility": ("Accessibility Statement | Summerville Accident Attorneys",
                      "How summervilleaccidentattorney.com and the Frost Law Group office are built to be usable by everyone, known limitations, and how to report a problem."),
    "thank-you": ("Thank You | Summerville Accident Attorneys",
                  "We received your message and will reply the same day. For anything urgent, call (843) 419-6653; injury calls are answered around the clock."),
    # car accident cluster
    CAR: ("Summerville Car Accident Lawyer | Free Consultation | Frost Law Group",
          "Injured in a car accident in Summerville, SC? A former judge and a former officer take on the insurer so you can heal. Free consultation, no fee unless we win."),
    CAR + "/what-to-do-after-a-car-accident-in-south-carolina": ("What to Do After a Car Accident in South Carolina | First 48 Hours",
        "Step by step: at the scene, at the hospital and in the first two days after a crash in Summerville or anywhere in SC, including the reports and calls to avoid."),
    CAR + "/is-south-carolina-an-at-fault-state": ("Is South Carolina an At-Fault State? | Car Accident Claims Explained",
        "Yes. South Carolina is an at-fault state: the driver who caused the crash, and that driver's insurer, pay for your injuries. What that means for your claim."),
    CAR + "/south-carolina-comparative-negligence": ("South Carolina Comparative Negligence | The 51% Rule Explained",
        "South Carolina's modified comparative negligence rule: recover if you were 50 percent or less at fault, reduced by your share. How insurers use it against you."),
    CAR + "/south-carolina-car-accident-statute-of-limitations": ("SC Car Accident Statute of Limitations | 3 Years, With Exceptions",
        "Three years from a South Carolina car accident to file suit, two years if a government vehicle or agency is involved, and different rules for minors and deaths."),
    CAR + "/south-carolina-car-accident-laws": ("South Carolina Car Accident Laws, Explained | Frost Law Group",
        "The SC laws that decide a crash claim: minimum insurance, the duty to stop and report, the seat-belt rule, the texting and hands-free laws, comparative fault."),
    CAR + "/should-i-talk-to-the-other-drivers-insurance-company": ("Should I Talk to the Other Driver's Insurance Company? | SC",
        "No, not before you talk to a lawyer. Why the adjuster calls so fast, what a recorded statement is used for, what you owe your own insurer, and what to say."),
    CAR + "/uninsured-motorist-accidents": ("Hit by an Uninsured or Underinsured Driver in SC? | UM & UIM Claims",
        "When the driver who hit you in Summerville or Goose Creek has no insurance or too little: how SC's UM and UIM coverage pays, stacking, and mistakes to avoid."),
    CAR + "/hit-and-run-accidents": ("Hit-and-Run Accident Lawyer | Summerville & Goose Creek, SC",
        "Hit by a driver who left the scene in Summerville, Goose Creek or North Charleston? How hit-and-run drivers are found, and how your UM coverage pays if not."),
    CAR + "/distracted-driving-accidents": ("Distracted Driving Accident Lawyer | Summerville & Goose Creek, SC",
        "Hit by a driver who was texting or on the phone? How SC's texting ban and hands-free law affect your claim, and how the phone records are obtained."),
    "practice-areas/drunk-driving-accidents": ("Hit by a Drunk Driver in Summerville, SC? | Frost Law Group",
        "If a drunk driver hit you in Summerville or Goose Creek, SC removes the cap on punitive damages and the bar that overserved may be liable. How the claim works."),
    "practice-areas/rideshare-accidents": ("Summerville Uber & Lyft Accident Lawyer | Frost Law Group",
        "Injured in an Uber or Lyft in Summerville, as a passenger, another driver or a pedestrian? Which rideshare policy applies and how the $1 million coverage works."),
    CAR + "/delivery-driver-accidents": ("Delivery Driver Accidents in Summerville, SC | Amazon, FedEx, UPS",
        "Hit by an Amazon, FedEx, UPS or food-delivery driver in Summerville? Which company's insurance applies, and what injured delivery drivers themselves can claim."),
    CAR + "/auto-injury-assessment-after-a-crash": ("Auto Injury Assessment in Summerville, SC | After a Crash",
        "Where to get evaluated after a car accident in Summerville, what to tell the provider, why same-day care matters, and how the bills get paid meanwhile."),
    CAR + "/where-crashes-happen-in-summerville": ("Where Car Accidents Happen in Summerville, SC | I-26, 17-A & More",
        "The Summerville roads and intersections where crashes cluster, who investigates each, and what the location means for your claim: I-26, 17-A, Dorchester Road."),
    # other hubs and spokes
    "practice-areas/truck-accidents": ("Summerville Truck Accident Lawyer | 18-Wheeler Crash Attorneys",
        "Hit by a tractor-trailer on I-26 or Highway 78? Summerville truck accident lawyers who preserve the logs, black-box data and video before the carrier does."),
    "practice-areas/truck-accidents/who-is-liable-in-a-truck-accident": ("Who Is Liable in a Truck Accident in South Carolina? | Frost Law Group",
        "Who pays after a tractor-trailer crash: the driver, the carrier, the truck owner, the broker, the shipper or the mechanic. How SC apportions fault among them."),
    "practice-areas/motorcycle-accidents": ("Summerville Motorcycle Accident Lawyer | Frost Law Group",
        "Injured riding in Summerville? Motorcycle accident lawyers who counter the bias against riders, explain SC's helmet law and prove the driver was at fault."),
    "practice-areas/motorcycle-accidents/south-carolina-motorcycle-helmet-law": ("South Carolina Motorcycle Helmet Law | Who Must Wear One",
        "South Carolina requires helmets and eye protection only for riders under 21. What the law says, and how not wearing a helmet affects an injury claim."),
    "practice-areas/pedestrian-accidents": ("Summerville Pedestrian Accident Lawyer | Hit by a Car in SC",
        "Hit by a car while walking or cycling in Summerville or North Charleston? SC's crosswalk and due-care rules, comparative fault, and where the coverage is."),
    "practice-areas/dog-bites": ("Summerville Dog Bite Lawyer | SC Strict-Liability Claims",
        "Bitten by a dog in Summerville, Goose Creek or Knightsville? South Carolina's strict-liability statute, homeowner's insurance, children's scarring claims."),
    "practice-areas/dog-bites/south-carolina-dog-bite-law": ("South Carolina Dog Bite Law | Strict Liability Under § 47-3-110",
        "What South Carolina's dog bite statute says: the owner or keeper is strictly liable when a dog bites a person lawfully present; provocation is the main defense."),
    "practice-areas/dog-bites/child-bitten-by-a-dog": ("My Child Was Bitten by a Neighbor's Dog in SC | What to Do",
        "When a child is bitten by a neighbor's dog in Summerville: medical care, animal control, the owner's homeowner's insurance, scar revision, a minor's settlement."),
    "practice-areas/dog-bites/does-homeowners-insurance-cover-dog-bites": ("Does Homeowner's Insurance Cover Dog Bites in SC? | Who Pays",
        "Usually yes. How a dog-bite claim is paid by the owner's homeowner's or renter's coverage in South Carolina, breed exclusions, and cases with no insurance."),
    "practice-areas/slip-and-fall": ("Summerville Slip & Fall Lawyer | Premises Liability | Frost Law Group",
        "Hurt in a fall at a store, restaurant or apartment in Summerville? What SC requires you to prove, the open-and-obvious defense, and the video to request now."),
    "practice-areas/workers-compensation": ("Summerville Workers' Compensation Lawyer | Frost Law Group",
        "Hurt on the job in Summerville or Ladson? What SC workers' comp pays, the 90-day notice rule, denied claims, and third-party claims that pay more."),
    "practice-areas/catastrophic-injuries": ("Catastrophic Injury Lawyer in Summerville, SC | Frost Law Group",
        "Brain injury, spinal cord injury, amputation or burns: Summerville lawyers who build the life-care plan, find every policy and value the decades ahead."),
    "practice-areas/wrongful-death": ("Summerville Wrongful Death Lawyer | Frost Law Group",
        "Lost a family member in a crash or other preventable accident? Who brings a SC wrongful death claim, what it pays, the survival action, and how we help."),
    "practice-areas/wrongful-death/south-carolina-wrongful-death-statute": ("South Carolina Wrongful Death Statute, Explained | § 15-51-10",
        "What SC's wrongful death statute provides: who files, who benefits, what damages are recoverable, the three-year deadline, and how the survival action differs."),
    # communities
    "areas/summerville": ("Summerville Car Accident & Injury Lawyer | Frost Law Group",
        "Injured in a crash in Summerville, SC? Who writes the report, which hospital treats trauma, which court hears the case, and how we help. Free consultation."),
    "areas/goose-creek": ("Goose Creek Car Accident Lawyer | Frost Law Group",
        "Injured in a crash in Goose Creek, SC? Who writes the report, which hospital treats trauma, which Berkeley County court hears the case, and how we help."),
    "areas/ladson": ("Ladson Car Accident & Personal Injury Lawyer | Frost Law Group",
        "Injured in a crash in Ladson, SC? Which county you were in, who writes the report, which hospital treats trauma, and how Frost Law Group's injury lawyers help."),
    "areas/north-charleston": ("North Charleston Car Accident & Injury Lawyer | Frost Law Group",
        "Injured in a crash in North Charleston, SC? Who writes the report, where trauma is treated, which Charleston County court hears the case, and how we help."),
    "areas/charleston": ("Charleston Car Accident & Personal Injury Lawyer | Frost Law Group",
        "Injured in a crash in Charleston, SC? Who writes the report, where trauma is treated, which court hears the case, and how Frost Law Group's injury lawyers help."),
    "areas/mount-pleasant": ("Mount Pleasant Car Accident & Injury Lawyer | Frost Law Group",
        "Injured in a crash in Mount Pleasant, SC? Who writes the report, where trauma is treated, which court hears the case, and how our injury lawyers help."),
    "areas/moncks-corner": ("Moncks Corner Car Accident & Injury Lawyer | Frost Law Group",
        "Injured in a crash in Moncks Corner, SC? Who writes the report, where trauma is treated, which Berkeley County court hears the case, and how we help."),
    "areas/walterboro": ("Walterboro Car Accident & Personal Injury Lawyer | Frost Law Group",
        "Injured in a crash in Walterboro or on I-95 in Colleton County? Who writes the report, where trauma is treated, which court hears the case, and how we help."),
    "areas/west-ashley": ("West Ashley Car Accident & Injury Lawyer | Frost Law Group",
        "Injured in a crash in West Ashley? Who writes the report, where trauma is treated, which Charleston County court hears the case, and how we help."),
    # blog
    "blog/i-26-crash-summerville-who-writes-the-report": ("Crash on I-26 Near Summerville: Who Writes the Report | Frost Law",
        "After a crash on I-26 near Summerville the Highway Patrol writes the report, not the town. What the FR-10 is, how to get the TR-310, why the mile marker counts."),
    "blog/dog-bite-summerville-neighborhood-what-parents-should-know": ("A Dog Bite in a Summerville Neighborhood: What Parents Should Know",
        "The loose dog, the child on a bike, the neighbor who says it never bit before. What South Carolina's strict-liability law says, who pays, and what to do first."),
    "blog/motorcycle-season-lowcountry-helmet-law-your-claim": ("Motorcycle Season in the Lowcountry: The Helmet Question | Frost Law",
        "Riders 21 and over may ride without a helmet in South Carolina. What that means for your claim when a driver turns left in front of you, and what insurers say."),
    "blog/hit-by-an-uninsured-driver-goose-creek-your-own-policy": ("Hit by an Uninsured Driver in Goose Creek? Your Own Policy Pays",
        "Why so many Goose Creek crashes involve uninsured drivers, and how South Carolina's UM and UIM coverage pays when theirs does not. The mistakes that forfeit it."),
    # answer pages from the keyword and community research
    CAR + "/how-to-get-your-south-carolina-accident-report": ("How to Get Your South Carolina Accident Report | FR-10 & TR-310",
        "How to get your car accident report in South Carolina: what the FR-10 is, how to request the TR-310 from the SCDMV or the police, and what to do if it is wrong."),
    CAR + "/car-accident-without-a-police-report": ("Car Accident Without a Police Report in SC | Can You Still Claim?",
        "Yes, but it is harder. How a claim works in South Carolina when no officer came, the FR-309 you must file within 15 days, the hit-and-run exception, and proof."),
    CAR + "/how-long-after-a-car-accident-can-you-claim-injury": ("How Long After a Car Accident Can You Claim Injury in SC?",
        "You felt fine, then hurt days later. What South Carolina law allows, what insurers argue about a treatment gap, and why the practical answer is this week."),
    CAR + "/car-accident-that-was-not-your-fault": ("Car Accident Not Your Fault in South Carolina | What Happens Next",
        "After a crash that was not your fault in SC: how the other insurer handles your car, the rental, total-loss value and diminished value, and what never to sign."),
    CAR + "/minor-car-accident-what-to-do": ("Minor Car Accident in South Carolina | Do You Need a Lawyer?",
        "A fender-bender in Summerville: what SC requires you to do, when you can handle it yourself, when a minor crash is not minor, and an honest answer on lawyers."),
    CAR + "/what-happens-if-the-accident-was-my-fault": ("Car Accident That Was Your Fault in South Carolina | What Happens",
        "If you caused a crash in SC: what your liability coverage does, what happens if you are sued, and why you may still recover for your own injuries."),
    CAR + "/rear-end-collisions": ("Rear-End Collision Lawyer | Summerville, SC | Whiplash & Fault",
        "Rear-ended on Main Street, Dorchester Road or I-26? Who is at fault in a SC rear-end crash, the sudden-stop defense, whiplash claims and the low-speed myth."),
    CAR + "/how-much-is-my-car-accident-case-worth": ("How Much Is My Car Accident Case Worth in South Carolina?",
        "How a SC car accident claim is actually valued: medical costs, lost income, pain and suffering, fault, policy limits and liens. Why settlement averages mislead."),
    CAR + "/how-long-does-a-car-accident-case-take": ("How Long Does a Car Accident Case Take in South Carolina?",
        "A realistic timeline for a SC car accident claim: treatment, demand, negotiation, lawsuit, mediation and trial in Dorchester, Berkeley or Charleston County."),
    "questions": ("Questions Summerville Drivers Ask After a Crash | Frost Law Group",
        "Every question answered on this site in one place: after a crash, dog bite, fall or work injury in Summerville and the Lowcountry. SC law in plain English."),
    # spanish
    "es/abogado-de-accidentes": ("Abogado de Accidentes de Carro en Summerville, SC | Frost Law Group",
        "¿Lesionado en un accidente de carro en Summerville, Goose Creek o North Charleston? Abogados de accidentes. Consulta gratis, no cobramos a menos que ganemos."),
}
